version: '3'

services:
  # app:
  #   build:
  #     context: app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   restart: on-failure
  #   environment:
  #     MESSAGING_URL: tcp://artemis:61616
  #     MESSAGING_USER: sqills # we can use secrets to handle this user and password
  #     MESSAGING_PASS: sqills # we can use secret etc
  #     MESSAGING_TOPIC: sqills_topic
  #     JAVA_OPTIONS: -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
  #   depends_on:
  #     - artemis
  

  artemis:
    build:
      context: artemis
      dockerfile: Dockerfile
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      ARTEMIS_USERNAME: sqills
      ARTEMIS_PASSWORD: sqills